// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUscMtgOaEo6Y3kylZPhgGA2A-qnfeETk',
    appId: '1:1007786744590:web:2de867c4f0feb30f62155f',
    messagingSenderId: '1007786744590',
    projectId: 'chatme-c321d',
    authDomain: 'chatme-c321d.firebaseapp.com',
    storageBucket: 'chatme-c321d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKWXjKYbGBsp5fHKyQ92_UrCKgFUzwFiY',
    appId: '1:1007786744590:android:d0f741f9b3a07ffb62155f',
    messagingSenderId: '1007786744590',
    projectId: 'chatme-c321d',
    storageBucket: 'chatme-c321d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPCmx3S2ats6LXbLcPur1zj_M0UsTrw_M',
    appId: '1:1007786744590:ios:2cf6bf4a6f5484b062155f',
    messagingSenderId: '1007786744590',
    projectId: 'chatme-c321d',
    storageBucket: 'chatme-c321d.appspot.com',
    iosClientId: '1007786744590-ivug46teso21vrr4sb7gmu2gs1ap3bnn.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatmeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPCmx3S2ats6LXbLcPur1zj_M0UsTrw_M',
    appId: '1:1007786744590:ios:e35f5a7e32e6f4f362155f',
    messagingSenderId: '1007786744590',
    projectId: 'chatme-c321d',
    storageBucket: 'chatme-c321d.appspot.com',
    iosClientId: '1007786744590-43fd305fnfe8qciqvlpd3i8hskb4kkn8.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatmeApp.RunnerTests',
  );
}
